version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - "/home/mongodb_data:/data/db"
    ports:
      - "27017:27017"
    container_name: mongo
