version: "3.1"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    container_name: nginx
    volumes:
      - "$PWD/html:/usr/share/nginx/html"
      - "$PWD/config:/etc/nginx/conf.d"